import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { root, run } from './lib.ts';

const host = process.env.BUILD_TARGET === 'host';
const build = join(root, 'build', host ? 'core-local' : 'core-release');
const core = resolve(process.env.CORE_BINARY || join(build, host ? 'face-library' : 'face-core'));
if (!process.env.CORE_BINARY) {
  if (host) {
    await run(['cmake', '-S', 'apps/backend/engine', '-B', build,
      '-DCMAKE_BUILD_TYPE=Release', '-DFACE_LIBRARY_TESTS=ON',
      ...(process.env.OpenCV_DIR ? [`-DOpenCV_DIR=${process.env.OpenCV_DIR}`] : []),
      ...(process.env.MBEDTLS_ROOT ? [`-DMBEDTLS_ROOT=${process.env.MBEDTLS_ROOT}`] : []),
    ]);
    await run(['cmake', '--build', build, '-j2']);
  } else {
    await run(['docker', 'buildx', 'build', '--platform', 'linux/amd64',
      '-f', 'Dockerfile.build', '--output', `type=local,dest=${build}`, '.']);
  }
}
if (!await Bun.file(core).exists()) throw Error(`Missing compiled face engine: ${core}`);
await run([process.execPath, 'run', '--filter', '@repo/frontend', 'build']);
const frontend = join(root, 'apps/frontend/dist');
const files = (await readdir(frontend)).sort();
const imports = files.map((name, i) =>
  `import a${i} from ${JSON.stringify(join(frontend, name))} with { type: 'file' };`);
imports.push(`import embeddedCore from ${JSON.stringify(core)} with { type: 'file' };`);
await writeFile(join(root, 'apps/backend/src/assets.gen.ts'),
  '// @ts-nocheck -- generated by scripts/build.ts; validated by Bun.\n' + imports.join('\n') +
  '\nexport const coreAsset = embeddedCore;\nexport const assets = new Map<string,string>([' +
  files.map((name, i) => `[${JSON.stringify('/' + name)}, a${i}]`).join(',') + ']);\n');
const outfile = resolve(process.env.APP_BINARY || join(root, 'apps/backend/dist/face-library'));
await mkdir(resolve(outfile, '..'), { recursive: true });
const result = await Bun.build({
  entrypoints: [join(root, 'apps/backend/src/server.ts')], target: 'bun', minify: true,
  compile: { outfile, ...(host ? {} : { target: 'bun-linux-x64' as const }) },
});
if (!result.success) throw new AggregateError(result.logs, 'Application build failed');
const size = Bun.file(outfile).size;
if (size > 256 * 1024 * 1024) throw Error('Binary exceeds Nibrun’s 256 MiB limit');
console.log(`Built ${outfile} (${(size / 1048576).toFixed(1)} MiB)`);
